# pubspec.yaml

name: agropilot
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^5.0.3
  
  # For GPS location retrieval
  geolocator: ^12.0.0
  # For making API calls to OpenWeatherMap
  http: ^1.2.1
  # For saving farm-specific input
  shared_preferences: ^2.2.3
  # For converting location coordinates to a human-readable address
  geocoding: ^3.0.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  