// lib/services/district_mapping.dart

const Map<String, String> districtMapping = {
  'Ahmednagar': 'Ahmednagar',
  'Akola': 'Akola',
  'Amravati': 'Amravati',
  'Aurangabad': 'Aurangabad',
  'Beed': 'Beed',
  'Bhandara': 'Bhandara',
  'Buldhana': 'Buldhana',
  'Chandrapur': 'Chandrapur',
  'Dhule': 'Dhule',
  'Gadchiroli': 'Gadchiroli',
  'Gondia': 'Gondia',
  'Hingoli': 'Hingoli',
  'Jalgaon': 'Jalgaon',
  'Jalna': 'Jalna',
  'Kolhapur': 'Kolhapur',
  'Latur': 'Latur',
  'Nagpur': 'Nagpur',
  'Nanded': 'Nanded',
  'Nandurbar': 'Nandurbar',
  'Nashik': 'Nashik',
  'Osmanabad': 'Osmanabad',
  'Palghar': 'Palghar',
  'Parbhani': 'Parbhani',
  'Pune': 'Pune',
  'Raigad': 'Raigad',
  'Sangli': 'Sangli',
  'Satara': 'Satara',
  'Solapur': 'Solapur',
  'Wardha': 'Wardha',
  'Washim': 'Washim',
  'Yavatmal': 'Yavatmal',
  'Ratnagiri': 'Ratnagiri',
  'Thane': 'Thane',
  'Sindhudurg': 'Sindhudurg',
  // Add any API-specific alternate names if needed
  'Vasai-Virar': 'Palghar',
  'Mumbai Suburban': 'Thane',
};
